namespace:
  name: prod

service:
  port: 80
  type: ClusterIP

image:
    repository: nginx
    tag: 1.17.0
  
replicaCount: 2
  
resources:
  requests:
    CPU: 70m
    memory: 256Mi

configmap:
  data: "version:1.17.0"

