namespace:
  name: demo

service:
  port: 8111
  type: ClusterIP
  
image:
  repository: nginx
  tag: alphine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    CPU: 50m
    memory: 256Mi

configmap:
  data: "version:alpine"

